language: csharp
solution: compiler/compiler.sln
install:
  - nuget restore compiler/compiler.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - cd compiler
  - xbuild /p:TargetFrameworkVersion="v4.5"  /p:Configuration=Debug compiler.sln
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then mono ./packages/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./bin/Debug/compiler.dll; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "yL6e8FToCKXU4/34ART+pjGKSYZoTPdygcNUyXKUWA+8/T93Bx4KnmxI9bKdqbyz/dI5+hhXahW8lqPru+PehR/JqpDsBG9r7VTvDbPac8vnYX9EpRFYYVq7t8W2vXgQQj66gCkMerTDvJnz1/Yvai20rJNdSmf3M5/SF752pJf52pv5ZN6Y5i5zXWSJXkal6c9iyXATXTDb+i7ETlaoPPnvwGEXDjmzboiP1/s+W7IIbqWcz6O0SA6f0lrjNdgfzq5Cto/pXOPTLsWpWchE5oidEj2SVLmXZqcynWpmvedT+OmIt1xyZC8/FnyAu1cGvdYpT20lN+gcQz/edVkAm26GJlNSdDUwOda4Kpqk00KWIuBSBSVT2rwMEA622QugzlG8gtDqJh73TPFJimyxaXqSZECxwliOM1n4yZCV/XHahj9XMYeGLhFQaaJEvsjYFWbPerCkEvYycptLFNfrOTjYBoh2rXqywgIPRpDZk/N+N+gB/LhKzRai2O2wBPl44VezcTQmN5hxk2YBJgWtI/ClIUAQ4eAFMqKAZm8jEi2rSUBK1Ix0xl0CdGStBNOTED8AFCPcVDEno3TyLIaw40a3VTo33sjLBGUOAevAqhxA1diMdS7XoY5hPgyfw66jJpVgnZln83CMQFH8B0lMKXir3ij4z8K7KYAKTqnTvBs="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "ilovepi/Compiler"
      description: "A Project for Evaluating Compiler Algoithms and Design"
    notification_email: pk1574@gmail.com
    build_command_prepend: "xbuild /p:TargetFrameworkVersion="v4.5"  /p:Configuration=Debug compiler.sln"
    build_command:   "xbuild /p:TargetFrameworkVersion="v4.5"  /p:Configuration=Debug compiler.sln"
    branch_pattern: coverity_scan
